### ISSUE TITLE
Sticks at line 1311  Gui says starting 

### ISSUE THREAD

**Issue by MaterPaul** [DarkMatterCore/wad2bin#10]
Hello 
New to programming
I am trying to put a DLC Just dance 2 wad on SD card.
I running Windows 7 
Python 3 for x86
pip3 
I downloaded wad2bin master I am using 
[DLC INSTRUCTIONS (IMPORTANT - MUST READ).docx](https://github.com/DarkMatterCore/wad2bin/files/6575456/DLC.INSTRUCTIONS.IMPORTANT.-.MUST.READ.docx)
It sticks at line 1311 
(https://user-images.githubusercontent.com/85164484/120306687-5f234600-c2d2-11eb-9e5b-7196c9d3bcc3.jpg)
I have tried changing wad2bin name from wad2bin windows x86.exe to wad2bin that didn't help anything I tried putting everthing in one folder. Still sticks. Help needed thanks.

**Comment by MaterPaul** [comment]
Got it working. I was using gui.py with wad2bin-windows-x86.exe as in guide instead of using just wad2bin-gui-windows-x86.exe
Please can someone make a gui windows x86 for Github ETHena I have tried running on python but with no programming background it's hopeless.

**Comment by DarkMatterCore** [comment]
Fixed in fabda9c6575afdc6c03bac903ac9c3c1dc0fc9bf. The Python script now lets the user know where to put the wad2bin binary if it can't be found.
