### ISSUE TITLE
Rock Band 2 wad2bin process failed

### ISSUE THREAD

**Issue by homebrewer1111** [DarkMatterCore/wad2bin#12]
Hi, 

I'm trying to convert Rock Band 2 (Europe) WAD files taken from the Mariocube Repository into BIN files using wad2bin, but the process fails. I have had no issues previously when using wad2bin with the Mariocube Repository's Rock Band 3 (Europe) and Guitar Hero (Europe) WAD files, but I can't figure out what the problem is here. 

An extract of the log is included below for reference. Please can you help with this issue? Am I doing something wrong, or could the WAD file be broken (and where else can I obtain RB2 WAD files if so)?

-----------------------
Starting...

wad2bin v0.8 (c) DarkMatterCore.

Built on: 15:48:35 Aug 12 2021.

Keydata and device certificate successfully loaded.

WAD header:

  Header size:            0x20 (InstallablePackage).

  Type:                   "Is" (Normal).

  Version:                0 (InstallablePackage).

  Certificate chain size: 0xa00.

  Ticket size:            0x2a4.

  TMD size:               0x4978.

  Content data size:      0x15d7000.

Certificate #1:

  Signature type:         0x00010001 (RSA-2048 + SHA-1).

  Signature issuer:       Root-CA00000001.

  Public key type:        0x00000001 (RSA-2048).

  Name:                   XS00000003.

  Date:                   0xf1b89fd1.

Certificate #2:

  Signature type:         0x00010000 (RSA-4096 + SHA-1).

  Signature issuer:       Root.

  Public key type:        0x00000001 (RSA-2048).

  Name:                   CA00000001.

  Date:                   0x5bfa7d5c.

Certificate #3:

  Signature type:         0x00010001 (RSA-2048 + SHA-1).

  Signature issuer:       Root-CA00000001.

  Public key type:        0x00000001 (RSA-2048).

  Name:                   CP00000004.

  Date:                   0xf1b8a064.

Ticket:

  Signature type:         0x00010001 (RSA-2048 + SHA-1).

  Signature issuer:       Root-CA00000001-XS00000003.

cryptoVerifyRsaSignature: RSA signature verification failed! Bad data? (-16640).

  Encrypted titlekey:     775e6256d06f29b42352f3dc72c55be7.

  ID:                     0001660c56b80e3c.

  Console ID:             00000000.

  Title ID:               00010005735a4350.

  Title Version:          23.

  Common Key Index:       0x00 (Normal).

  Titlekey IV:            00010005735a43500000000000000000.

  Decrypted titlekey:     2290ac694bc222eaf6fca58749e1c350.

Ticket fakesigned (not issued for target console).

Title Metadata (TMD):

  Signature type:         0x00010001 (RSA-2048 + SHA-1).

  Signature issuer:       Root-CA00000001-CP00000004.

  Version:                0.

  Target System:          0x00 (Wii).

  System Version:         0000000100000025.

  Title ID:               00010005735a4350.

  Title Type:             0x00000019.

  Publisher:              69.

  Region:                 0x0002.

  Title Version:          25.

  Content Count:          509.

  Boot Index:             511.

TMD signature is valid.

wadUnpackContentFromInstallablePackage: SHA-1 checksum mismatch!

Data at WAD offset 0x5680 doesn't match content with index 0000.

*** Cut for space ***

Content with index 01f4 is bigger than the rest of the WAD package (doesn't match data at offset 0x5680). Skipping...

wadUnpackContentFromInstallablePackage: SHA-1 checksum mismatch!

*** Cut for space ***

Data at WAD offset 0x5680 doesn't match content with index 01fb.

wadUnpackContentFromInstallablePackage: SHA-1 checksum mismatch!

wadUnpackInstallablePackage: Failed to save decrypted content file "000001fc.app" from "C:/Users/homebrewer1111/Downloads/Rock Band 2 - AFI - Miss Murder (Europe) (DLC) (RB2) (sZC).wad"!

Process failed!

**Comment by DarkMatterCore** [comment]
Some WADs from the MarioCube repository are either incomplete or malformed - there's not much I can do about it. Just some days ago, another user stumbled upon another malformed RB2 WAD.

Ask the maintainers to double check / reupload the data.

**Comment by gius** [comment]
Try to use Parent TID of RB3 instead of RB2
