### ISSUE TITLE
[Feature Request] Generate a ticket from keys if there is none or if it's invalid

### ISSUE THREAD

**Issue by zurgeg** [DarkMatterCore/wad2bin#15]
Helpful if you're like me, and don't like patching IOS, or if you can't for whatever reason.

**Comment by zurgeg** [comment]
It also might be nice to make it an option (i.e., `--gentik`) instead of doing it automatically, in case you want to keep the invalid ticket for whatever reason.

**Comment by DarkMatterCore** [comment]
If possible, please elaborate on what you mean by generating a ticket using keys.

**Comment by zurgeg** [comment]
> If possible, please elaborate on what you mean by generating a ticket using keys.

If I'm not misunderstanding (which, I probably am), the ticket signs and encrypts the WAD, right? So with the keys (which are required anyways), we can generate a valid one for that Wii.

**Comment by DarkMatterCore** [comment]
Not really, nope. The [ticket](https://wiibrew.org/wiki/Ticket) itself is signed by Nintendo's certificate chain and that's it -- WAD contents are encrypted using the plaintext titlekey from the ticket, which is stored in encrypted form using the Wii's common key.

WAD contents aren't signed at all. Even though the [TMD](https://wiibrew.org/wiki/TMD) is, which holds the metadata for all WAD contents, the content metadata area isn't part of the signed area.

**Comment by DarkMatterCore** [comment]
Furthermore, generating valid (e.g. non-fakesigned) tickets for any Wii console would require access to the private RSA keys used by Nintendo to sign both the Ticket and the TMD. These keys remain unknown, and can't be dumped from any Wii because they just aren't there.

Using a patched IOS is a must unless the WAD comes from your own console and was not fakesigned.

**Comment by DarkMatterCore** [comment]
@zurgeg Glad to help, mate.
