### ISSUE TITLE
Wad2Bin freezes

### ISSUE THREAD

**Issue by ThePercyUK** [DarkMatterCore/wad2bin#17]
Hello,
Great app, and love the gui. However, I've long struggled to get Wad2Bin working. 
currently it seems to freeze after showing this in the gui:
-----------------------
Starting...

wad2bin v0.6 (c) DarkMatterCore.

Built: 21:40:12 Jun 18 2020.

Usage: F:\wad2bin.exe <keys file> <device.cert> <input WAD> <output dir>

Paths must not exceed 259 characters. Relative paths are supported.

The required directory tree for the *.bin file(s) will be created at the output directory.

You can set your SD card root directory as the output directory.

 The command prompt shows:
C:\Users\user\AppData\Local\Programs\Python\Python39\lib\subprocess.py:931: RuntimeWarning: line buffering (buffering=1) isn't supported in binary mode, the default buffer size will be used
  self.stdin = io.open(p2cwrite, 'wb', bufsize)
C:\Users\user\AppData\Local\Programs\Python\Python39\lib\subprocess.py:937: RuntimeWarning: line buffering (buffering=1) isn't supported in binary mode, the default buffer size will be used
  self.stdout = io.open(c2pread, 'rb', bufsize)

This version (0.6) has previously worked with an older laptop, so I'm a little baffled. However this is the same error i have recieved trying to use it on a newer laptop. This was using Rock Band WAD with title ID (00010000535A4150), but the error seems to happen with any DLC WAD. Incidentally, It does seem to work if I leave the Title ID blank.

The newer version (0.8) has consistently given the same error on both systems:

GUI:

-----------------------
Starting...

Command prompt:
C:\Users\user\AppData\Local\Programs\Python\Python39\lib\subprocess.py:937: RuntimeWarning: line buffering (buffering=1) isn't supported in binary mode, the default buffer size will be used
  self.stdout = io.open(c2pread, 'rb', bufsize)
Exception in thread Thread-2:
Traceback (most recent call last):
  File "C:\Users\user\AppData\Local\Programs\Python\Python39\lib\threading.py", line 954, in _bootstrap_inner
    self.run()
  File "C:\Users\user\AppData\Local\Programs\Python\Python39\lib\threading.py", line 892, in run
    self._target(*self._args, **self._kwargs)
  File "G:\WAD2BIN20\gui.py", line 518, in execute_script
    p = subprocess.Popen(args,
  File "C:\Users\user\AppData\Local\Programs\Python\Python39\lib\subprocess.py", line 947, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\user\AppData\Local\Programs\Python\Python39\lib\subprocess.py", line 1416, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] The system cannot find the file specified

**Comment by DarkMatterCore** [comment]
@ThePercyUK Please update wad2bin using one of the more recent builds from the releases page, then try again.

**Comment by DarkMatterCore** [comment]
@ThePercyUK I'll temporarily close this issue. Feel free to reopen it if you can still reproduce it using the latest release.
