### ISSUE TITLE
Just Dance 2 Stuck

### ISSUE THREAD

**Issue by ThatsAnotherJ** [DarkMatterCore/wad2bin#20]
So I tried this method with Just Dance 2 and now its just stuck on "Refreshing the song list" and "Reading the SD Card" on a neverending loop. Anyone know a fix?

**Comment by DarkMatterCore** [comment]
Just as the readme states, trial and error is encouraged, sadly. There's just a lot of different cIOS + parent TID + titlekey combinations.

Try using a different cIOS, a different parent Title ID or a different titlekey option.

**Comment by ThatsAnotherJ** [comment]
Thing is, this basically broke my Just Dance 2 unless I take out the SD Card. I tried re installing the game and clearing all data I can  find, but it is still broken

**Comment by DarkMatterCore** [comment]
Honestly, I fail to see how SD card data alone (or the lack of it, thereof, as you state) could generate this condition.

Are you even using a patched IOS to launch the game? You haven't even stated the launch method you're using -- is it a legitimate disc? Is it a burned backup? Is it a backup stored on a USB drive and/or the SD card itself?

As stated before, there's a lot of different aspects you could check on your end before blaming the tool. The source codd is open for a reason.
