### ISSUE TITLE
Band Hero wads and DLC support

### ISSUE THREAD

**Issue by warno77** [DarkMatterCore/wad2bin#21]
Thanks for wad2bin. It is awesome! 
One question is if there is support for Band Hero DLC and what the Parent TID is for it?
I think they may be cross-compatible with Guitar Hero World Tour but not sure.
Thanks again for the hard work on this.

**Comment by DarkMatterCore** [comment]
@warno77 Hi there, mate. Thanks, I'm glad to know you like this project. 🙂

The program should let you generate .bin files for Band Hero as long as you provide its TID as the parent TID -- feel free to try it out. Parent TIDs aren't hardcoded in wad2bin, only actual DLC TIDs are.

**Comment by warno77** [comment]
Any idea what the TID for Band Hero is?
I used the Band Hero wad and used the Guitar Hero 5 TID and it worked. Unfortunately all the Band Hero DLC seems to be the songs from the actual Band Hero game (which I already have) and not the additional DLC content (not any fault of yours).
Thanks again for the help!

**Comment by DarkMatterCore** [comment]
According to [GameTDB](https://www.gametdb.com/Wii/SXFE52), the TID seems to be `00010000-535846xx` (`SXFx`), where `x` represents a region code.

**Comment by DarkMatterCore** [comment]
If there are no further questions, I'll close this issue. Feel free to reopen it if a problem arises.
