### ISSUE TITLE
Korean key

### ISSUE THREAD

**Issue by homebrewchannel** [DarkMatterCore/wad2bin#33]
My keys obtained by xyzzy doesn't have a Korean key, so what do i do about that?

**Comment by homebrewchannel** [comment]
![image](https://github.com/user-attachments/assets/76d4c475-2499-451b-9656-a074e8bad8bf)
![image](https://github.com/user-attachments/assets/ebbfada1-1a0b-4a5f-ae86-3708c1dd8efc)
my files for reference

**Comment by DarkMatterCore** [comment]
@homebrewchannel I'm sorry, but I had to delete your comment. Displaying the keys out in the open kinda defeats the purpose of the application -- and I'd like to avoid any kind of issues whenever possible.

As for your concern, the application can't dump what your console doesn't have. The Korean common key is stored in the SEEPROM of Korean consoles, and it is only dumped if it's actually available. Hope that helps.

**Comment by homebrewchannel** [comment]
2 things, 1, you are absolutely correct, and 2, what do i put in the section for the korean code?

**Comment by DarkMatterCore** [comment]
Don't put anything at all. You shouldn't need it, anyway -- unless you're specifically working with Korean WADs, in which case, well, you should already own a Korean Wii to begin with.

**Comment by homebrewchannel** [comment]
ok, thanks!

**Comment by homebrewchannel** [comment]
same with the vWii common code, right? because i have a real Wii

**Comment by DarkMatterCore** [comment]
> same with the vWii common code, right? because i have a real Wii

Yes

**Comment by homebrewchannel** [comment]
sorry to be a pain, but what do i do with this? 
# Set this to the C compiler name/alias you wish to use.
CC		:=	gcc

# Leave EXEEXT empty if not compiling for Windows.
EXEEXT	:=	.exe
for reference im on a windows 11 machine and im using mingw+mys2 and git

**Comment by homebrewchannel** [comment]
i dont want to be a pain in the [tuchus](https://www.merriam-webster.com/dictionary/tuchus#:~:text=slang,tuchus%20looks%20in%20a%20bikini.) but i tried running it and this showed up. 
![image](https://github.com/user-attachments/assets/d0b07ce1-6a45-4f37-bb40-c48ff46e3b81)
i tried with a non decompressed version and a decompressed version
it's ok if you dont want to deal with this right now, just get to it when you want to.
Edit: i think i know what's wrong, let me test it
Edit 2: i was wrong

**Comment by homebrewchannel** [comment]
@DarkMatterCore do you know what happened here?

**Comment by DarkMatterCore** [comment]
@homebrewchannel It looks like you're trying to use a non-WAD file as the input WAD, which will simply not work at all.

**Comment by homebrewchannel** [comment]
@DarkMatterCore how do i get a wad for a game's savedata?

**Comment by DarkMatterCore** [comment]
What are you exactly trying to accomplish? I feel like wad2bin isn't what you'd want to use here.

**Comment by homebrewchannel** [comment]
Good question, I’m trying to edit savedata but I can’t decipher it

**Comment by DarkMatterCore** [comment]
> Good question, I’m trying to edit savedata but I can’t decipher it

Yeah, wad2bin isn't really a savedata tool.

Judging by your screenshot, I'd say yout Wii savedata already is in extracted form, which means you now need to look for a savedata tool that's specifically tailored to the game those files belong to.

Hope that helps.
