### ISSUE TITLE
Trying to convert DLC WAD

### ISSUE THREAD

**Issue by coreflake1** [DarkMatterCore/wad2bin#5]
Hi, 

I'm having a bit of an issue with the latest version of wad2bin. 
I'm trying to convert dlc wads to bin. 
If I add the title ID the tool does not start. 
I tried both GUI & commandline. 

any idea ?

**Comment by DarkMatterCore** [comment]
@coreflake1 Hi there. Could you please provide a screenshot and a copy of the full command you're using?

**Comment by DarkMatterCore** [comment]
@coreflake1 I'm closing this issue for the time being. Feel free to reopen it if you ever want/need to.
