### ISSUE TITLE
Converting DLC WAD for WiiWare game

### ISSUE THREAD

**Issue by jackemled** [DarkMatterCore/wad2bin#7]
I'm trying to convert a DLC WAD for a WiiWare game. I get error code -9 when trying to install to SD Card. Wad2bin says "A duplicate file name exists, or the file cannot be found.", but I do have the file in the wad2bin folder & I do not have a duplicate, unless it thinks the WAD for the game itself, which I already converted, is a duplicate.
[installation_error_log.txt](https://github.com/DarkMatterCore/wad2bin/files/6171506/installation_error_log.txt)
![image](https://user-images.githubusercontent.com/80965042/111790169-4d680000-8898-11eb-99df-9490ac208808.png)

**Comment by DarkMatterCore** [comment]
Please provide a valid error log from wad2bin itself. I can't do anything with RiiConnect24's output.

**Comment by DarkMatterCore** [comment]
I'm closing this issue for the time being. Feel free to reopen it if you ever get a valid error log.
